output_dir: ./experiments/

dataset:
  class: CiteSeerLinkPrediction
  path: ~/datasets/homogeneous_graphs/

task:
  class: LinkPrediction
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: no
    remove_one_hop: yes
    symmetric: yes
  criterion: bce
  num_negative: 1
  strict_negative: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 40

metric: auroc